### ISSUE TITLE
Find a way to DIRECTLY inform the user that a mensa name is not found...

### ISSUE THREAD

**Issue by mmonimon** [mmonimon/mensa-skill#59]
... and prompting for another one, instead of letting the user go through the whole slot elicitation and finally telling "sorry, essenspläne für mensa gollum hab ich nicht im angebot"

**Comment by mmonimon** [comment]
Slot validation is the answer!!!!!!!!! PR coming soon :)

**Comment by mmonimon** [comment]
https://github.com/mmonimon/mensa-skill/pull/61

**Comment by bogdankostic** [comment]
fixed by #61
